# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text=b'eg:Fiat', max_length=255, verbose_name='Car Brand')),
                ('kilometers', models.IntegerField()),
                ('price', models.IntegerField()),
                ('hp', models.IntegerField(verbose_name='HP')),
                ('cc', models.IntegerField()),
                ('gearbox', models.NullBooleanField(choices=[(True, b'Manual'), (False, b'Auto')], default=False, verbose_name='Gear box type')),
                ('color', models.CharField(help_text=b'eg:red', max_length=255, verbose_name='Color')),
                ('euro_type', models.CharField(blank=True, help_text=b'eg:euro 5', max_length=10, null=True, verbose_name='Euro type')),
                ('license_plate', models.CharField(blank=True, help_text=b'eg:KZP1234', max_length=10, null=True, verbose_name='license')),
                ('serial', models.CharField(blank=True, help_text=b"Car's serial number", max_length=255, null=True)),
                ('fuel', models.CharField(help_text=b'eg:Gas', max_length=20, verbose_name='Car fuel')),
                ('owners_before', models.IntegerField(help_text=b'How many owners before you?')),
                ('movement', models.NullBooleanField(choices=[(None, b'4X4'), (True, b'FWD'), (False, b'BCK')], default=True)),
                ('manufactured', models.DateTimeField()),
                ('airbags', models.IntegerField(help_text=b'If no airbag type 0')),
                ('dors', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.Owner')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CarOwnerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Owner')),
            ],
        ),
    ]
