# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text=b'eg:Fiat', max_length=255, verbose_name='Car Brand')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
