# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Car Brand: eg:Fiat')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
