# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='car',
        ),
    ]
