# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 16:55
from __future__ import unicode_literals

import csm.utils.unique
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'', max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(default=b'', max_length=255, verbose_name='Last Name')),
                ('gender', models.NullBooleanField(choices=[(None, b'Gender'), (True, b'Female'), (False, b'Male')], default=None, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, help_text=b"Owner's birth date", null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text=b"Owner's email", max_length=254)),
                ('serial', models.CharField(blank=True, default=csm.utils.unique.unique_id, help_text=b"Owner's serial number", max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='companies.Company')),
            ],
        ),
    ]
