# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 15:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
                ('owned_Cars', django.db.models.manager.Manager()),
            ],
        ),
    ]
